const results = [
{id:1,category: 'football', title:'Football - BBC Sport', link:'https://www.bbc.co.uk/sport/football', description:'Football news, scores, results, fixtures and videos from the Premier League, Championship, European and World Football from the BBC.'},
{id:2,category: 'football', title:'Football - Wikipedia', link:'https://en.wikipedia.org/wiki/Football', description:'Football is a family of team sports that involve, to varying degrees, kicking a ball to score a goal. Unqualified, the word football normally means the form ...'},
{id:3,category: 'football', title:'Football Games, Results, Scores, Transfers, News | Sky Sports', link:'https://www.skysports.com/football', description:'Sky Sports Football - Live games, scores, latest football news, transfers, results, fixtures and team news from the Premier to the Champions League.'},
{id:4,category: 'football', title:'Soccer news, match reports and fixtures | The Guardian', link:'https://www.theguardian.com/football', description:'Football news, results, fixtures, blogs, podcasts and comment on the Premier League, European and World football from the Guardian, the worlds leading...'},
{id:5,category: 'football', title:'The website for the English Football Association', link:'https://www.thefa.com/', description:'Whats happening in the grassroots game? Stay up-to-date or find out how you can participate in football via our England Football pages. The FA ...'},
{id:6,category: 'football', title:'Football News, Transfers, Opinion - talkSPORT', link:'https://talksport.com/football/', description:'Football news, transfer rumours, opinion, fixtures, results, live scores and videos from the Premier League, EFL, Europe and beyond.'},
{id:7,category: 'football', title:'Football news - transfers, fixtures, scores, pictures | The Sun', link:'https://www.thesun.co.uk/sport/football/', description:'Latest football news and transfer rumours. Get your team updates, match results and upcoming fixtures. Stay ahead of the game plus pictures and videos with ...'},
{id:8,category: 'football', title:'football | History, Rules, & Significant Players | Britannica', link:'https://www.britannica.com/sports/football-soccer', description:'16 Jun 2022 — football, also called association football or soccer, game in which two teams of 11 players, using any part of their bodies except their ...'},
{id:9,category: 'food', title:'Just Eat: Order takeaway online from 30000+ food delivery ...', link:'https://www.just-eat.co.uk/', description:'Order from local restaurants and takeaways online with Just Eat, the UKs leader in food delivery with over 30000+ restaurant menus offering Pizza, Chinese, ...'},
{id:10,category: 'food', title:'Food - Wikipedia', link:'https://en.wikipedia.org/wiki/Food', description:'Food is any substance consumed to provide nutritional support for an organism. Food is usually of plant, animal, or fungal origin, and contains essential ...'},
{id:11,category: 'food', title:'THE 10 BEST Restaurants & Places to Eat in Orpington 2022', link:'https://www.tripadvisor.co.uk/Restaurants-g1934185-Orpington_Bromley_Greater_London_England.html', description:'Best Dining in Orpington, Bromley: See 16299 Tripadvisor traveller reviews of 172 Orpington restaurants and search by cuisine, price, location, and more.'},
{id:12,category: 'food', title:'BBC Good Food', link:'https://www.bbcgoodfood.com/', description:'Were all about good recipes, and about quality home cooking that everyone can enjoy.'},
{id:13,category: 'food', title:'Slow Food in the UK - Celebrate whats on your plate!', link:'https://www.slowfood.org.uk/', description:'Many in the Slow Food community are likely familiar with the term food desert, used to describe an area that has limited access to fresh, healthy and affordable ...'},
{id:14,category: 'food', title:'Slow Food International', link:'https://www.slowfood.com/', description:'Slow Food is a global, grassroots organization, founded in 1989 to prevent the disappearance of local food cultures and traditions, counteract the rise of ...'},
{id:15,category: 'food', title:'Deliveroo - Takeaway Food Delivery from Local Restaurants', link:'https://deliveroo.co.uk/', description:'We deliver your takeouts or essential groceries from the best-rated local partners straight to your door. Download our app or order online. Food. We Get It.'},
{id:16,category: 'food', title:'Food - BuzzFeed', link:'https://www.buzzfeed.com/food', description:'Eat Nothing But Sweets For A Day And We will Reveal Which Savory Food Your Personality Most Embodies.'},

]

module.exports = results;